### ISSUE TITLE
怎么看有没有进行登录密码爆破，以及有验证码的情况下如何爆破

### ISSUE THREAD

**Issue by lishixin7777** [youki992/VscanPlus#2]

**Comment by youki992** [comment]
有验证码情况下跳过爆破，弱口令的爆破代码功能在/brute/admin_brute.go中，通过状态码和关键字来判断爆破结果
![image](https://github.com/youki992/VscanPlus/assets/60724505/91ad69ab-b172-4f35-a81b-e799b047a49f)

**Comment by lishixin7777** [comment]
good,其实可以调用ddddocr去识别验证码爆破
