### ISSUE TITLE
乱码

### ISSUE THREAD

**Issue by DamnVanish** [youki992/VscanPlus#7]
Windows11上面运行会有乱码
想这样：
[[34mINF[0m] Port scan over,web scan starting
还有：这样的中文乱码
[200] [Office Anywhere 2017鐗� 缃戠粶鏅鸿兘鍔炲叕绯荤粺] [tongda-oa] [3163]

**Comment by youki992** [comment]
师傅，我也是Win11的系统但是运行输出正常，是不是您电脑字符集或者编码显示有问题
![image](https://github.com/youki992/VscanPlus/assets/60724505/b0b1c2e6-4adf-4e0f-87f1-9d81bd23739a)

**Comment by DamnVanish** [comment]
确实有可能，不过我用其他工具没有出现过这种现象，好像是有个别字符的才会乱码
